use_frameworks!

platform :ios, '8.0'

target 'YZDownloadManager_Example' do
  pod 'YZDownloadManager', :path => '../'

  target 'YZDownloadManager_Tests' do
    inherit! :search_paths

    
  end
end
